name: open_media_station_audiobook
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  icons_plus: ^5.0.0
  media_kit: ^1.1.11 # Primary package.
  media_kit_libs_audio: ^1.0.5 # Native audio dependencies.
  open_media_station_base: ^0.0.5
    # path: ../open_media_station_base

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  msix: ^3.16.8

flutter:
  uses-material-design: true
  assets:
    - assets/myapp.png

msix_config:
  display_name: Open Media Station - Audiobook
  publisher_display_name: LNA-DEV
  # publisher: CN=7B47E609-6C44-44B4-9DFA-CF58A4704989
  # identity_name: 54515LNA-DEV.OpenMediaStation-MovieTV
  msix_version: 0.0.1.0
  store: true
  logo_path: ./AppIcon.png
  # capabilities: internetClient, location, microphone, webcam